### ISSUE TITLE
harden-telegram/server/tests red on main: watchdog API drift + pytest import breaks the pre-commit test hook for every commit

### ISSUE THREAD

**Issue by idvorkin-ai-tools** [idvorkin/chop-conventions#200]
`skills/harden-telegram/server/tests` fails at the current `upstream/main` tip (cf3f6dc), which makes the pre-commit `test` hook (`just fast-test`, `always_run: true`) fail every commit in the repo regardless of what the commit touches — `just fast-test`'s `all(...)` short-circuits there, so later suites (image-explore, machine-doctor, pr-hygiene, up-to-date) don't even run.

Observed on C-5001, system Python 3.14:

- `test_two_process_killtest.py` — loader `ImportError: No module named 'pytest'` (system-Python unittest discovery can't import a pytest-dependent module; every other suite in the repo is unittest/stdlib-only).
- `test_watchdog.py::TestMainEntryValidation` (3 errors) — `AttributeError: module 'watchdog' has no attribute 'main'`; the tests target an entry point that `skills/harden-telegram/tools/watchdog.py` no longer has.
- `test_watchdog.py::TestRecoverySequence` (2 failures, 1 error) — expected send-keys sequence (`Escape`, `C-u`, `/reload-plugins`) no longer matches `do_recovery`'s actual behavior.

Looks like test/implementation drift: the suite encodes an older watchdog API. All other fast-test dirs pass individually (bulk 57, cost-impact 45, delegate-to-other-repo 39, harden-telegram/tools 135, image-explore 12, machine-doctor 62, pr-hygiene 31, up-to-date 72).

Until fixed, every commit needs `SKIP=test` (used and documented in #199), which silently drops the fast-test gate for the suites that DO work. Fix options: update the watchdog tests to the current API, and either convert `test_two_process_killtest.py` to stdlib unittest or exclude pytest-dependent files from the justfile's discovery.

Related: #109 (earlier pre-commit `test`-hook hazard).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
